# At the beginning of this video  
1. We were able to use @jit decorator to speedup our code. 
2. We were also able to use @jit decorator to parallelize our code.

In [1]:
import numpy as np

In [6]:
def do_some_op(x, y, z):
    return x + y + z

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10, 20, 30],[40, 50, 60]])
c = 100

In [8]:
# [1, 2, 3] + [[10, 20, 30], + 100
# [1, 2, 3] +  [40, 50, 60]]
do_some_op(arr1, arr2, c)

array([[111, 122, 133],
       [141, 152, 163]])

# Using @vectorize decorator

In [9]:
from numba import vectorize, int64

In [16]:
# Eager Compilation
@vectorize([int64(int64, int64, int64)])
def do_some_op_eager(x, y, z):
    return x + y + z

In [17]:
do_some_op_eager(arr1, arr2, c)

array([[111, 122, 133],
       [141, 152, 163]])

In [15]:
# Lazy compilation
@vectorize
def do_some_op(x, y, z):
    return x + y + z

In [14]:
do_some_op(arr1, arr2, c)

array([[111, 122, 133],
       [141, 152, 163]])

# By the end of this video  
1. We will be able to @vectorize decorator to write universal numpy functions.  
2. We will understand how eager compilation works.