# At the start of this video  
1. We were able to create/intialise numpy arrays.  

# 1. Slicing

In [2]:
import numpy as np

In [6]:
my_np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [10]:
my_np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
my_np_array[:2]   # All elements before row 2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Before ',' we telling to take all rows
# After ',' we are asking for the first column only
my_np_array[:, :1]  

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [13]:
my_np_array[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
my_np_array[:,1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [16]:
my_np_array[1:3, 1:3]

array([[5, 6],
       [8, 9]])

# 2. Integer Array Indexing

In [17]:
my_np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [18]:
my_np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
my_np_array[[0, 1, 2], [0, 1, 2]]

array([1, 5, 9])

In [23]:
my_np_array[[0, 1, 2, 3], [1, 1, 2, 1]]

array([ 2,  5,  9, 11])

## 3. Boolean Masking

In [24]:
my_np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [28]:
my_np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
bool_mask = my_np_array%2==0

In [26]:
bool_mask

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [27]:
my_np_array[bool_mask]

array([ 2,  4,  6,  8, 10, 12])

In [29]:
bool_mask2 = my_np_array%5==0

In [30]:
bool_mask2

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [ True, False, False]])

In [31]:
my_np_array[bool_mask2]

array([ 5, 10])

### Reference: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

# By the end of this video  
1. We will be able to do slicing and indexing on numpy arrays.
2. We will implement boolean masking on numpy arrays.